# This GitHub Actions workflow builds and pushes the Docker image to ghcr.io.
# It triggers on every push to the 'main' branch.

name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Grant permissions for the GITHUB_TOKEN to upload packages (Docker images)
    permissions:
      contents: read
      packages: write

    steps:
      # 1. Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Log in to GitHub Container Registry (ghcr.io)
      #    Uses the built-in GITHUB_TOKEN for authentication.
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Build the Docker image and push it to GHCR
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/guacamole-xfce:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

